apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tsrd-blob-pvc
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: azureblob-fuse-premium
  resources:
    requests:
      storage: 10Gi
